added optional wind conditions
dmcinnes/MMM-forecast-io pull request #23
Opened 2018-11-24 02:41 UTC by morozgrafix

Added a way to optionally display wind speed and direction

It looks like this:
![image](https://user-images.githubusercontent.com/1007608/48963789-6625ac80-ef4f-11e8-91b0-d5e3245d576f.png)

2018-12-03 04:22 UTC, dmcinnes requested changes
Looks great! Just a suggestion on how to avoid the if/elses.

2018-12-03 04:22 UTC, dmcinnes commented on MMM-forecast-io.js
> +    }
I think all these if/else statements could be avoided. How about divide the wind bearing (plus 11.25) by 22.5 to get an index on an Array with the `cardinalDirection`? `['N', 'NNE', 'NE', ...`

2018-12-03 04:22 UTC, dmcinnes commented on README.md
> +    <tr>
Thanks for this!

2018-12-07 10:19 UTC, morozgrafix commented on MMM-forecast-io.js
> +    }
Good point. I will change that logic.

2018-12-08 02:58 UTC, morozgrafix commented
Cardinal Directions logic is changed and hopefully simplified it a bit. Thanks!

2019-07-22 03:36 UTC, dmcinnes commented
Thanks! Sorry lagging on reviewing.

2019-07-22 03:36 UTC, merged